POST http://localhost:3000/fox HTTP/1.1
content-type: application/json

{
    "note": "yyeeahh a super secret note..",
    "date": "Friday, 4 November 2022"
}


### 

POST http://localhost:3000/example HTTP/1.1
content-type: application/json

{

}

### 

POST http://localhost:3001/example HTTP/1.1
content-type: application/json
authorization: bearer jwt_user_token_2345

{

}